### ISSUE TITLE
Response to malformed DNS API response

### ISSUE THREAD

**Issue by robcza** [whalebone/sinkit-core#108]
Response code to DNS API must be 200 in case core just does not understand the input - e.g. invalid domain format, invalid characters/encoding

Such responses trigger the fail safe mechanism in the resolver for no reason (the core is not under exceptional load and is operating normally).

**Comment by Karm** [comment]
I believe this is fixed at least partially by sanitization on Resolver's side: https://github.com/whalebone/godns/blob/LR/sinkit.go#L43
