### ISSUE TITLE
Custom list logging

### ISSUE THREAD

**Issue by robcza** [whalebone/sinkit-core#109]
Logging for black/audit lists is completely missing. Hits into the custom lists have to be logged in the same manner as regular IoC hits

**Comment by Karm** [comment]
@robcza Pls, test karm/sinkit-core:1.0.20 and close the issue if it's O.K.

**Comment by robcza** [comment]
@Karm still missing the IoC placeholder that would carry the category information. In this case I would suggest "user" or "custom" category instead of regular "malware", "blacklist", etc.

**Comment by Karm** [comment]
Fixed in https://github.com/whalebone/sinkit-core/pull/115

**Comment by robcza** [comment]
As discussed on meeting, we won't create new IoCs, just placeholder on the level of the log record.

**Comment by Karm** [comment]
@robcza Close?

**Comment by Karm** [comment]
Closing. It is fixed and verified by Rob.
