### ISSUE TITLE
Items are not removed from custom lists

### ISSUE THREAD

**Issue by robcza** [whalebone/sinkit-core#111]
Items are not removed from custom list cache on portal request. Steps to reproduce:
- add domains to custom blacklist: <domain1>, <domain2>, <domain3>
- check that <domain2> is sinkholed based on request
- remove <domain2> from custom blacklist
- <domain2> is still sinkholed

**Comment by Karm** [comment]
@robcza Pls, test karm/sinkit-core:1.0.20 and close the issue if it's O.K.

**Comment by robcza** [comment]
@Karm @rattuscz tested right now:
1. xxx.com was on custom blacklist
2. removed xxx.com from custom blacklist
3. xxx.com still sinkholed after 10 minutes

**Comment by Karm** [comment]
@robcza IMHO fixed in portal.

**Comment by robcza** [comment]
Tested several times manually, no issue detected, closing.
