### ISSUE TITLE
Recent whitelist records count

### ISSUE THREAD

**Issue by robcza** [whalebone/sinkit-core#117]
API call to count whitelist records added in last X (e.g. 24) hours. Will be used for whitelist ingest monitoring to avoid complete whitelist expiration.

**Comment by Karm** [comment]
HotRod stats just return general numbers of records - this issue needs more work, some lookup of soon-to-be-evicted Infinispan records.

**Comment by Karm** [comment]
Tracked in https://github.com/whalebone/sinkit-core/issues/121
