### ISSUE TITLE
Generate Blacklist with fqdns that users have set for logging or blocking

### ISSUE THREAD

**Issue by Karm** [whalebone/sinkit-core#118]

**Comment by Karm** [comment]
curl core-core-ingest-1:8080/sinkit/rest/protostream/whitewithoutcustom/

/opt/sinkit-core/whiteWithoutCustom.bin  is smaller than /opt/sinkit-core/whitelist.bin, which is a good sanity check :)

**Comment by robcza** [comment]
Logic should reversed blacklist + custom lists

**Comment by Karm** [comment]
Done.

**Comment by Karm** [comment]
Although, needs Cloud Resolver counterpart: https://github.com/whalebone/godns/issues/16
