### ISSUE TITLE
Integration tests: Remove hardcoded JSON in CoreTest.java and open issues for test errors

### ISSUE THREAD

**Issue by Karm** [whalebone/sinkit-core#141]
@hugeox Hardcoded JSON constructs should be moved to separate JSON text files so as [CoreTest.java](https://github.com/whalebone/sinkit-core/blob/master/integration-tests/src/test/java/biz/karms/sinkit/tests/core/CoreTest.java) is free of such abominations. Next, see what fails and why and start opening Github issues for failures.

FYI, There are 3 major directions each test can take:
### Simple unit test
There are very few cases this helps us in this particular project. Unit tests would be great for CIDRUtils, CRC64 and there it likely ends.
### Unit tests with some Mockito
This should present the majority or our tests, I would like to kindly ask you move/port any tests you see fit to this setup. See Mockito usages both in Sinkit and in https://github.com/Karm/ispn-dump2proto. The gist is that you describe the behaviour of a certain method and Mockito "fakes" such behaviour for you in the test runtime. It gives you the power to fake ElasticSearch or Logstash or Infinispan presence without actually running those dependencies.
### Integration test
More or less the aforementioned, but with real services. Integration test should live inside the EAR deployment via Arquillian, real Infinispan should be running via Docker compose.

**Comment by hugeox** [comment]
Do you have anything to help with initializing all the environment variables?

**Comment by hugeox** [comment]
Could you also please elaborate on what I should do with the unit tests with Mockito? At the moment they all pass. What do you mean by " I would like to kindly ask you move/port any tests you see fit to this setup." ?

**Comment by hugeox** [comment]
Solved in #147
