### ISSUE TITLE
Too long url which can't be used as cache key 

### ISSUE THREAD

**Issue by kozeltom** [whalebone/sinkit-core#30]
How to deal with too long urls that can't be used as cache key due to exceeding length of 255 characters (see http://ur1.ca/ncabg)

**Comment by kozeltom** [comment]
It's not so rare as it could seem to be. We have several those long urls. Probably we will need some hash with constant length to be used as cache key instead of plain ulr string.

**Comment by Karm** [comment]
Why would I need those in the cache anyway? :disappointed: Is there any upper boundary? I could talk the cache into using longer keys I guess...

**Comment by kozeltom** [comment]
@robcza pls your opinion?

**Comment by robcza** [comment]
Solution with hashes seems pretty much ok. Should we provide access throug the API, it could handle the hashing of the URL from the request and check the infinispan. We will have the full URL in the IoC archive anyway for further logging and analysis.

**Comment by Karm** [comment]
Done ages ago.
