### ISSUE TITLE
Black/White list matching for domains using wildcards

### ISSUE THREAD

**Issue by Karm** [whalebone/sinkit-core#38]
e.g. `foo.something.example.com` holds priority over general `*.example.com`.

**Comment by Karm** [comment]
@rattuscz @robcza over the years :smiley: the logic has been moving to the Resolver, IIUC. Can we close this? Should we tinker around matching wildcards on the Infinispan side?

**Comment by robcza** [comment]
At the moment, this is solved on the resolver side
