### ISSUE TITLE
Logging request fqdn and type

### ISSUE THREAD

**Issue by robcza** [whalebone/sinkit-core#65]
We have to log another two attributes to cover the needs of the analyst properly: 
- request.fqdn - for the cases when there is log created based on IP, we have to know, what was the original fqdn in the request, that was resolved to the IP
- request.type - it could be quite important for the analysis to know the particular DNS request type (A, MX, TXT, etc.)

Solving this issue will have to be done on three layers:
- extend information included in the API calls from the resolver @Karm 
- add the two attributes described above to the logging method @Karm 
- extend the logging index by these values (will be done automatically on the elasticsearch level) @kozeltom 

I think, we should keep this extensible, as there will likely be other changes based on user feedback

**Comment by kozeltom** [comment]
Disagree with the responsibilities. All the time from begginig I've been responsible for logging method, so I can't see a reason why it should have changed now:)

**Comment by robcza** [comment]
sorry @kozeltom  just improperly defined - I meant @Karm will have to call your logging function with these additional attributes :)

**Comment by kozeltom** [comment]
So:
- extend information included in the API calls from the resolver @Karm
- add the two attributes described above to the logging method @kozeltom

**Comment by robcza** [comment]
Yes, and @Karm has to actually call your method with those new attributes received from resolver

**Comment by Karm** [comment]
:sweat_smile:
