### ISSUE TITLE
Global whitelist

### ISSUE THREAD

**Issue by robcza** [whalebone/sinkit-core#70]
Global whitelist functionality should be implemented as follows:

1. There will dedicated cache for whitelist in infinispan @Karm 
2. This cache will be filled daily with Alexa top sites through Alexa free API https://aws.amazon.com/code/Alexa-Top-Sites/405 @Karm 
  - Downloaded lists will be global (no parameter) and country specific CZ
  - Records will be added to the list with TTL 10 days
3. Adding a new whitelisted record will remove any existing ioC of the same fqdn from the infinispan @Karm 
4. While adding new IoCs to the Core through API, whitelist cache is checked. Should there be an existing whitelist record, IoC is not added to the cache @kozeltom

**Comment by kozeltom** [comment]
Ad 4: IoC should not be stored in cache. But should it be stored in elastic anyway?

**Comment by robcza** [comment]
@kozeltom yes it should. Jut thinking, it would be nice to store it with an attribute { "whitelisted": "true" }
