### ISSUE TITLE
Add default values to selected env properties

### ISSUE THREAD

**Issue by Karm** [whalebone/sinkit-core#78]
This shouldn't happen:

    Caused by: java.lang.IllegalStateException: System property 'SINKIT_WHITELIST_VALID_HOURS' is not set

IMHO, one could use some lib for the task or crudely check in a way, e.g.:

       public static final String unwantedNameSuffix = (System.getenv().containsKey("SINKIT_UNWANTED_SINGLETON_NODE_SUFFIX")) ? System.getenv("SINKIT_UNWANTED_SINGLETON_NODE_SUFFIX") : "dns";

**Comment by kozeltom** [comment]
Disagree. Not a bug. This is correct behaviour. If you don't have set this system property, its better to fail during deployment than have there some unknown hardcoded value. Properly set environment is precondition for proper run of the app... IllegalStateException is thrown on purpose to enforce proper environment setting...

**Comment by Karm** [comment]
O.K.

**Comment by Karm** [comment]
Anyway, how about stopping the whole deployment? This way, it runs and merely spits exceptions....

**Comment by kozeltom** [comment]
Yep you're right. it would deserve to do this for all beans that need system envs
