### ISSUE TITLE
Very frequent: putHashPrefix: Hash prefix blablabla already contained in cache.

### ISSUE THREAD

**Issue by Karm** [whalebone/sinkit-core#86]
Is it really expected that these messages are very frequent?

`INFO  [biz.karms.sinkit.ejb.impl.GSBServiceEJB] (default task-69) putHashPrefix: Hash prefix blablabl already contained in cache.`
- either it ain't supposed to be happening very often (now easily 10 times a minute)
- or we should lover the logging level to FINE

WDYT?

**Comment by kozeltom** [comment]
Hmms, the question is why python module sends prefix that is already contained and why it is so often. Nevertheless for core it's not a problem. The FINE log level would be good solution.

**Comment by robcza** [comment]
Will check the python module

**Comment by Karm** [comment]
I don't think this is a problem anymore. If you feel differently, please, reopen.
